config/routes.rb
Rails.application.routes.draw do



  resources :users, except: [:new, :create, :index] do
    resources :outfits
  end

  resources :outfits do 
    resources :styles, only: [:index, :new, :create, :show, :edit]
  end


  resources :styles



  get '/welcome', to: "welcome#home", as: "welcome_page"
  root to: "welcome#home"

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'
  post '/logout' => 'sessions#destroy'

 



  get '/auth/facebook/callback', to: "sessions#create_with_fb"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/outfit.rb
class Outfit < ApplicationRecord

    default_scope { order(times_worn: :desc) }

    has_many :styles
    has_many :users, through: :styles
    

    # validate :is_title_case

    # before_validation :make_title_case

    # accepts_nested_attributes_for :styles

    

    validates :name, presence: true

    scope(:top_search, ->(query) {self.where("top LIKE ?", "%#{query}")})
    scope(:bottom_search, ->(query) {self.where("bottom LIKE ?", "%#{query}")})
    scope(:shoes_search, ->(query) {self.where("shoes LIKE ?", "%#{query}")})
    scope(:accessories_search, ->(query) {self.where("accessories LIKE ?", "%#{query}")})



    def self.attribute_search(attribute)
        where("top == ? or bottom == ? or shoes == ? or accessories == ?")
    end


    def styles_attributes=(attrs)

    attrs.values.each do |hash|
        if hash[:id]
            s = Style.find_by(id: hash[:id])
            s.update(hash)
        else
        self.styles.build(hash)
        end
    end
end


    def is_title_case
        if self.name != self.name.titlecase
            self.errors.add(:name, "must be title-cased")
        end

    end


    def make_title_case
        self.name = self.name.titlecase
    end


end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController

    before_action(:set_outfit, except: [ :index, :new, :create])
    before_action(:redirect_if_not_logged_in)
    
    layout "application"
   

    def index

        if params[:user_id]
            @user = User.find_by(id: params[:user_id])
            @outfits = @user.outfits
            
        elsif 
            if params[:searching_for]
            p = params[:searching_for]
            if p == "top"
                @outfits = Outfit.top_search(params[:query])
            elsif p == "bottom"
                @outfits = Outfit.bottom_search(params[:query])
            elsif p == "shoes"
                @outfits = Outfit.shoes_search(params[:query])
            elsif p == "accessories"
                @outfits = Outfit.accessories_search(params[:query])
            end 
        end
        else
            @outfits = Outfit.all 
        end
    end


    def show
        # @outfit = Outfit.find_by(id: params[:id])
    end


    def new
        @outfit = Outfit.new
        @outfit.styles.build(user: current_user)
        @styles = @outfit.styles.select{|s| s.user_id == current_user.id}
    end

    def create
        @outfit = Outfit.new(outfit_params)
        @outfit.styles.each {|s| s.user = current_user}
        if @outfit.save
            redirect_to outfit_path(@outfit)
        else
          @errors = ["Outfit Needs A ame, Please Try Again."]
          @styles = @outfit.styles.select{|m| m.user_id == current_user.id}
          render :new
        end
      end

      def edit
      end

  
    def update
        # @outfit = Outfit.find_by(id: params[:id])
        if @outfit.update(outfit_params)
            redirect_to outfits_path
        else
            render 'edit'
        end
    end

 

    def destroy
        @outfit.delete
        redirect_to root_path
    end
 

    private

    def outfit_params
        params.require(:outfit).permit(:id, :name, :top, :bottom, :shoes, :accessories, :times_worn, styles_attributes: [ :name, :era, :user_id])
    end

    def set_outfit
        @outfit = Outfit.find_by(id: params[:id])
    end



end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/views/outfits/_form.html.erb
<%=form_for @outfit do |f| %>
  <%= f.label "Name of Outfit:" %>
  <%= f.text_field :name %><br>
  <%= f.label "Top:" %>
  <%= f.text_field :top %><br>
  <%= f.label "Bottom:" %>
  <%= f.text_field :bottom %><br>
  <%= f.label "Shoes:" %>
  <%= f.text_field :shoes %><br>
  <%= f.label "Accessories:" %>
  <%= f.text_field :accessories %><br>
  <%= f.label "Times Worn:"%>
  <%= f.number_field :times_worn %> <br>

      <br>
    <%= f.submit "Submit"%>


  <%end%>

app/views/outfits/edit.html.erb
<%= render(partial: "application/errors", locals: {errors: @outfit.errors.full_messages})%>


<%= render 'form'%>

<%= link_to "Exit", root_path%>

app/views/outfits/index.html.erb
<h1> All Outfits </h1>

Search by Article of Clothing

<%= form_tag outfits_path, :method => "get" do %>
Search by
</span>
<span class="text-search">
<select name="searching_for" id="searching_for" class="searching_for">
  <option value="top">Top</option>
  <option value="bottom">Bottom</option>
  <option value="shoes">Shoes</option>
   <option value="accessories">Accessories</option>
</select> 
<%# Type:  %>
</span>
<%= text_field_tag :query, "", class: "search" %>
<span class="search-padding"></span>
<button class="search-button">Search</button>
<%end%>


<% @outfits.each do |outfit| %>

<div>
<h1><%= link_to outfit.name, outfit_path(outfit)%></h1>

<br>

</h3>
<%= outfit.top%>
<br>
<%= outfit.bottom%>
<br>
<%= outfit.shoes%>
<br>
<%= outfit.accessories%>
<br>
<%= outfit.times_worn%>
<br><h3>

<%end%>

app/views/outfits/new.html.erb
<h1> New Outfit </h1>


<% @errors && @errors.each do |e| %>
  <li><%=e%></li>
<%end%>


<%= render 'form'%>


<%= link_to "Exit", outfits_path %>

app/views/outfits/show.html.erb
<h1> Outfit Overview </h1>

<p>
<ul>

<h1><%=@outfit.name%></h1>
<%= @outfit.top%> |
<%= @outfit.bottom%> |
<%= @outfit.shoes%> |
<%= @outfit.accessories%>
<%= @outfit.times_worn%>
<br>
<br>



<%=link_to "Add a Style", new_outfit_style_path(@outfit)%>



<br>

<br>



<%= link_to "See Styles Associated with this Outfit", outfit_styles_path(@outfit)%>
<%@outfit.styles.each do |s|%>



<br>
<br>

<br>

<%= (s.user == current_user) ? (link_to "Edit Outfit", edit_outfit_path(@outfit)) : (nil)%>
<br>

<br>

<%= (s.user == current_user) ? (link_to "Delete outfit", outfit_path(@outfit), method: :delete, data: { confirm: "Are you sure you want to delete this outfit?"}) : (nil)  %>

<%end%>