config/routes.rb
Rails.application.routes.draw do



  resources :users, except: [:new, :create, :index] do
    resources :outfits
  end

  resources :outfits do 
    resources :styles, only: [:index, :new, :create, :show, :edit]
  end


  resources :styles



  get '/welcome', to: "welcome#home", as: "welcome_page"
  root to: "welcome#home"

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'
  post '/logout' => 'sessions#destroy'

 



  get '/auth/facebook/callback', to: "sessions#create_with_fb"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlatIron Wardrobe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
body {
  background-image: url('https://image.freepik.com/free-vector/interior-design-dressing-room-background_1308-54317.jpg');
    background-repeat: no-repeat;
   background-attachment: fixed;
   background-position: center center;
  background-size: 80% 80%;
}
</style>

<style>
body {color: black;}
h1   {color: black;}
p    {color: black;}
p    {color: black;}
</style>

 
<nav class="navbar navbar-inverse navbar-fixed-bottom">
  <div class="container-fluid">
     <% if logged_in?%>
  <%= link_to "Create A outfit", new_outfit_path, class: "navbar-brand" %>
  <%= link_to "All Outfits", outfits_path, class: "navbar-brand" %>
  <%= link_to "My outfits", user_outfits_path(current_user), class: "navbar-brand" %>
  <%= link_to "Create A Style", new_style_path(current_user), class: "navbar-brand" %>

  <%= link_to "Logout", logout_path, method: "destroy", class: "navbar-brand" %>

  <%else%>
  <%=button_to 'Sign Up With Facebook', "/auth/facebook"%> |  <%= link_to "Sign Up", signup_path %> | <%= link_to "Login",  login_path %>
  <% end %>

  </div>
</nav>
<head>
<body>

    <%= yield %>
 <body>
</html>